version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    # For development only - run as root user to avoid permission issues
    user: "0:0"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./next.config.js:/app/next.config.js
      - ./tsconfig.json:/app/tsconfig.json 